services:
  - type: web
    name: skin-lesion-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    timeout: 120  # Increase timeout if needed

  - type: worker
    name: celery-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A app.celery worker --loglevel=info
